### ISSUE TITLE
Standard Events/Hooks

### ISSUE THREAD

**Issue by JamesMGreene** [js-reporters/js-reporters#1]
We on the [QUnit](http://qunitjs.com/) team have been [discussing](https://github.com/jquery/qunit/issues/531) the possibility of working with other JS test frameworks that can be run client-side (e.g. Mocha, Jasmine, Intern, Buster, etc.) to agree upon a standard Reporter interface so that we could hopefully share Reporter plugins between testing frameworks.

This would most likely come in the form of:
 - a minimum viable set of standardly-named events
 - an associated standard set of data/details provided for each event
 - ~~an EventEmitter interface (`.on(...)`/`.off(...)`) _**OR**_ object with standard "hook" properties~~
     - _Discussion moved to #3_
 - ~~_maybe_ a standard-ish way to add a Reporter, e.g. `MyLib.addReporter(x)`, `MyLib.reporter = x;`, etc.~~
     - _Discussion moved to #3_
 - ~~a minimum viable set of standard test status types (e.g. pass, fail, skip, todo, pending, etc.)~~
     - _Discussion moved to #4_

Would you guys be interested in discussing this further with us?

Cross-reference issues:
 - https://github.com/jquery/qunit/issues/531  (original discussion)
 - https://github.com/visionmedia/mocha/issues/1326
 - https://github.com/pivotal/jasmine/issues/659
 - https://github.com/theintern/intern/issues/257
 - https://github.com/busterjs/buster/issues/419
 - https://github.com/caolan/nodeunit/issues/276
 - https://github.com/flatiron/vows/issues/313

**Comment by jzaefferer** [comment]
Intern 3.0 implemented a new interface for custom reporters. The event names from our draft match, but there's plenty additional events. Docs are here: https://theintern.github.io/intern/#custom-reporters

**Comment by jzaefferer** [comment]
Discussing `runEnd` event in #12. Includes discussion about data relevant for other events as well.

**Comment by boneskull** [comment]
ok, I'm sitting down rewriting our reporter interface, so I'm wondering if I should use the draft or what.  can we like, vote on it?

**Comment by jzaefferer** [comment]
@boneskull we don't have a formal voting process, maybe we don't need one. So far there were no objections to the draft event names. Intern 3 is implementing the names already, you could go ahead and do the same. You're also welcome to review the proposal for event data in #12 - your feedback would help get that finished!

**Comment by jzaefferer** [comment]
@boneskull any thoughts on the above? Are you going to use the proposed event names?

**Comment by boneskull** [comment]
Seems fine to me, but I'll cc @mochajs/mocha

**Comment by boneskull** [comment]
guess you can't do that.

**Comment by boneskull** [comment]
cc @travisjeffery @a8m @danielstjules @dasilvacontin @jbnicolai

**Comment by jbnicolai** [comment]
@boneskull thanks for the inclusion. I'll get back to this tomorrow when I've had time to have a closer look. Kudos on getting back to this, still think the /js-reporters/js-reporters project is awesome!
