### ISSUE TITLE
TapReporter needs circular ref filtering on JSON.stringify

### ISSUE THREAD

**Issue by krisselden** [js-reporters/js-reporters#104]

**Comment by trentmwillis** [comment]
Definitely a bug. It shouldn't be too hard to fix.

**Comment by Krinkle** [comment]
Similar issue fixed in Tape's TAP reporter:
https://github.com/substack/tape/pull/24

Mocha:
https://github.com/mochajs/mocha/commit/365dcd2600feb83d3c847751612e7c1ee149001d

node-tap:
https://github.com/tapjs/node-tap/commit/73aaa92787ef58417f12a4b8755b46dbf664c017

**Comment by zackthehuman** [comment]
I'd be happy to try and tackle this. I got bit by this 3 months ago and again by it today, resulting in a rather nasty `unhandledRejection` issue with QUnit.

**Comment by Krinkle** [comment]
@zackthehuman Go for it!
