### ISSUE TITLE
Google Summer of Code 2015

### ISSUE THREAD

**Issue by fcarstens** [js-reporters/js-reporters#11]
Hi all,

Good news: jQuery secured a Google Summer of Code slot this summer to get an initial standard established and implemented. I'm the lucky student who will work on this, so I quickly want to say hello and let you know what's planned. :smiley:
You can find a rough timeline  in my GSoC [proposal](http://www.google-melange.com/gsoc/proposal/public/google/gsoc2015/fcarstens/5629499534213120). There is still a month left before the actual GSoC coding period starts, but we already want to start slowly and I'll come up with an initial proposal for the event data similar to what @JamesMGreene did for event names (https://github.com/js-reporters/js-reporters/issues/1#issuecomment-54572441) soon. 

Cheers,
Franziska

**Comment by Jonahss** [comment]
:+1:  Awesome!

**Comment by jbnicolai** [comment]
That's great! :smile:

**Comment by jzaefferer** [comment]
:+1: First results can be seen in #12, more to come.
