### ISSUE TITLE
js-reporter does not recognize filtered test points when using QUnit.config.filter

### ISSUE THREAD

**Issue by muthu90ec** [js-reporters/js-reporters#113]
> ## Tell us about your runtime:
> * **QUnit version**: 2.9.1
> * **What environment are you running QUnit in? (e.g., browser, Node)**: node
> * **How are you running QUnit? (e.g., script, testem, Grunt)**: qunit cli
> 
> ## What are you trying to do?
> [js-reporter](https://github.com/js-reporters/js-reporters#readme) errors out when QUnit.config.filter is used. QUnit.config.filter works fine, but the printing portion errors out when using js-reporter.

**Comment by Krinkle** [comment]
I believe this is a bug in QUnit. Being worked on downstream at https://github.com/qunitjs/qunit/issues/1407.
