### ISSUE TITLE
tape?

### ISSUE THREAD

**Issue by ljharb** [js-reporters/js-reporters#118]
No idea what would be involved, but tape is more commonly used than most of the frameworks listed in the readme ¯\\\_(ツ)_/¯

**Comment by Krinkle** [comment]
Sure thing, we wouldn't want a spec that is incompatible or inconvenient with tape.

I haven't been looking into additional frameworks for a while as I hope between the ones we have active integration with now, that we cover all the main primitives in this space. I'm currently focussing on publishing the spec and getting adoption from reporter plugins, and orchestrations/runners. But, the plugin ecosystem around Karma and QUnit hasn't been super active now, so (early) adoption is getting harder to bootstrap. Mocha certainly takes the cake on popularity, but tape is huge!

I went and created a team for tape here, invited a few folks, and made you team maintainer. Feel free to invite more people any time.

From a quick look around, I think tape's use of lexical binding for nested tests and assertions, would produce a similar model as QUnit. Is that right? Would love to learn more about any semantic differences, perhaps at https://github.com/js-reporters/js-reporters/issues/117.

There's also definitely room for more adapters to allow for early adoption, prior to any implementation shipping in tape itself, and/or a additional [research section](https://github.com/js-reporters/js-reporters/blob/main/docs/frameworks.md) on tape as a framework.

Welcome ❤️

**Comment by ljharb** [comment]
I'm not familiar with QUnit at all, I'm afraid.

**Comment by Krinkle** [comment]
Thanks for sticking with me, and sorry it took so long. It's odd that it seems in the years prior adopting TAP in this way was never considered. While support for it in Node.js tools has been widespread for a while, actually seeing it used in CLI output by default is still pretty rare apart form tape and node-tap, and using it for browser communication while proven to be viable indeed seems rare beyond testling. But, I love it, let's give it our best.

Considering this closing, continuing at https://github.com/js-reporters/js-reporters/issues/133.
