### ISSUE TITLE
 Event Data

### ISSUE THREAD

**Issue by fcarstens** [js-reporters/js-reporters#12]
In this issue, I would like to focus on standardizing the event data format for the runEnd event. The runEnd event should provide a summary to integration tools when all tests are finished. First let's start with a look at the existing events (and please correct me if I'm wrong somewhere!).

### QUnit
`QUnit.done(function(details){}) ` provides a summary of the tests
```
{
    failed: 1, //number of assertions, not tests
    passed: 3,
    total: 4,
    runtime: 19
}
```
There is no information on passed and failed tests. 

### Mocha 
In contrast to QUnit, mocha's `end` event doesn't give information about the test data. However, we can use the global `suite end` event to get the raw data per test/suite and aggregate this for a summary:
```
{
    suites: [/* child suites (recursive) */],
    tests: [{ duration: 0, speed: "fast", state: "passed"}],
}
```
There is no information on passed and failed assertions.

### Jasmine
In Jasmine you get information on the test status only per test/spec, the total number of tests has to be counted manually during execution. The data for tests looks as follows:
```
{
    failedExpectations: [],
    passedExpectations: [],
    status: "failed" 
    // no information on current suite
}
```
In contrast to QUnit and mocha, we get information on passed and failed assertions/ expectations.

### Buster
Buster is most similar to QUnit. There's the `suite:end` event with the following data output:
```
{
    "contexts": 2, //buster context == (jasmine/mocha) suite
    "tests": 3,
    "errors": 0,
    "failures": 1,
    "assertions": 4,
    "timeouts": 0,
    "deferred": 0,
    "ok": false
}
```
### Summary
As we can see, the available event data varies greatly between the frameworks. Looking at the use-case of an integration tool, a summary as in QUnit or Buster seems to be most useful. This brings up two questions: 

1. Do we want to include information on assertions which cannot be provided by all frameworks (e.g. Mocha)?
2. Which level of detail is appropriate? Do we prefer QUnit's minimal style or do we want to provide as much information as Mocha does + summary?

**Comment by jzaefferer** [comment]
I mentioned in #1 that Intern 3 implemented a new reporter interface. It looks like that has a `runEnd` event that provides an `Executor` instance. I didn't find any information about that type, the [`Custom Exectutor` docs are still a todo](https://theintern.github.io/intern/#custom-executors). May need to dig into the implementation to find out more.

As for the open questions: Having a `runEnd` event provide aggregated results has the advantage that tools can subscribe to that event alone, without the need to aggregate data manually. The more detail available, the less likely the need to fall back to manual aggregation. Aggregating that data by default should have very little overhead for the test runner. For the consumer its trivial to ignore everything it doesn't care about.

With that in mind, there's a lot of room for the data. [Based on the events agreed upon so far](https://github.com/js-reporters/js-reporters#event-names), we have suites and tests. We can also expect every framework to deal with assertions, though as the Mocha example shows, that number might not be available. In addition to the main blocks `suite`, `test` and `assertion` (also referred to as "expectation") we have properties like `status` (or `state`) and optional properties like `runtime`  (or `duration`).

[On a related QUnit issue](https://github.com/jquery/qunit/issues/472) I suggested this structure:

```js
QUnit.on( "runEnd", function( details ) {
	details.tests.forEach(function( test ) {
		// Access test.name, test.moduleName, test.assertions
		// assertions is the same as in testDone
	});
});
```

The `details.tests` property matches what Mocha provides, though its properties don't.

With that there's plenty to investigate:

* What top-level properties to provide? `suites`? `tests`?
* What properties should `suites` have? References to other suites, to tests?
* What does a test consist of? Can it have other tests? While QUnit currently doesn't support nested tests, it certainly makes sense to provide a structure that supports recursion, QUnit can still provide a flat structure in that format.
* `status` vs `state`
* `duration` vs `runtime`
* Should everything have `total` properties? Inflates the API, but is also more convenient for the consumer than adding up `failed` and `passed`.

Some of this will be relevant for other events as well.

@fcarstens would be great if you could work through the above. I'll be (much more) around, so ping me on IRC or Skype, too.

For anyone else reading this: We've let this project sleep for a while, but we're still hoping for your participation!

**Comment by JamesMGreene** [comment]
Thanks for getting the ball rolling again, @fcarstens!

**Comment by fcarstens** [comment]
Here is a proposal for the event data structure which is heavily inspired by mocha: [data.js](https://github.com/fcarstens/js-test-examples/blob/master/data.js).
We have two basic entities: 
- **Tests**: a test holds basic information on a single test. What exactly we want to put in there needs to be seen, this is more of a stub now.
- **Suites**: a suite has three properties: 
  - name
  - tests: all tests that are direct children of the suite
  - childSuites: all suites that are direct children of the suite  

Furthermore a "global" suite exists which has all top-level suites as children. Based on that, the data which each event (testEnd, suiteEnd, runEnd) should provide comes out straightforward: an individual test for testEnd, the corresponding suite for suiteEnd and the global suite for runEnd.

For example, [this](https://github.com/fcarstens/js-test-examples/blob/master/qunit/test.js) QUnit test or [this](https://github.com/fcarstens/js-test-examples/blob/master/mocha/test.js) Mocha test would result in the data structure at [data.js#L54-L60](https://github.com/fcarstens/js-test-examples/blob/5c957b100502d34b98c04bb3a4e34fe5448996f9/data.js#L54-L60).

Representing the data in this recursive structure has the benefit that it's easy to draw a tree of nested tests (as in Mocha or Jasmine). There are two use-cases remaining for which we want to cater as well:

1. Providing a summary: Every suite gets a `.getTotal()` method that provides aggregated results.
2. Providing a flat list of all tests: Every suite gets a `.getAllTest()` method which provides a flat list of all tests. We may want to include a "suiteName" attribute for each test then.

-------------------------------

If we can agree on this, there are two questions left to answer:
1. Which attributes should be included in the aggregated suite summary? (`suite.getTotal()`)
2. Which attributes does a test have? Is `name`, `status`, `runtime` (or however we want to phrase them) sufficient?

**Comment by jzaefferer** [comment]
These methods would have to be mapped to static data structures to represent them in JSON, though that should be straight-forward enough.

Adding `suiteName` to each test sounds fine, too.

To your questions: Whatever the individual properties are, I have a strong preference to avoid generic and ambiguous names like `passed`. We can have `passedAssertions`, `passedTests` and `passedSuites` instead. Which of those, and their siblings we have include at what level, still needs to be answered. QUnit's tendency to report total assertions is pretty unique (probably not a good thing). Would be useful to have an overview of the event data provided by various frameworks. That would help answer both questions.

**Comment by fcarstens** [comment]
Here's a complete proposal based on https://github.com/js-reporters/js-reporters/issues/12#issuecomment-112470619: the basic structure are the suite and test objects as described above. The following table lists what other frameworks provide and what we want to do for js-reporters.


### Aggregated test results 

| Suite Summary              | QUnit   | Mocha* | Jasmine* | Buster                     | Intern          | JS Reporters                                        |
|---------------------|---------|--------|----------|----------------------------|-----------------|-----------------------------------------------------|
| failed assertions   | failed  | -      | -        | -                          | -               | -                                                   |
| passed assertions   | passed  | -      | -        | -                          | -               | -                                                   |
| total assertions    | total   | -      | -        | assertions                 | -               | -                                                   |
| runtime/duration[1] | runtime | -      | -        | -                          | timeElapsed     | runtime                                             |
| total suites        | -       | -      | -        | contexts                   | -               | ?                                       |
| total tests         | -       | -      | -        | tests                      | numTests        | ?                                        |
| failed tests        | -       | -      | -        | errors/ failures/ timeouts | numFailedTests  | ?  |
| ignored tests       | -       | -      | -        | deferred                   | numSkippedTests | ? |
| status              | -       | -      | -        | ok (boolean)               | -               | status (enum)                                       |
*Mocha and Jasmine don’t provide aggregated summaries (only unaggregated details, which we provide as well (see above))

### Attributes per test

| testEnd                    | Qunit             | Mocha                          | Jasmine                                     | Buster                   | Intern               | JS Reporters    |
|----------------------------|-------------------|--------------------------------|---------------------------------------------|--------------------------|----------------------|-----------------|
| test name                  | name (string)     | title (string)                 | description (string)                        | name (string)            | name (string)        | testName        |
| module name                | module (string)   | -                              | fullName (module name + test name) (string) | -                        | -                    | suiteName       |
| filename                   | source (string)   | file (null/ string)            | -                                           | -                        | -                    | stacktrace      |
| runtime/duration           | runtime (number)  | duration (number)              | -                                           | -                        | timeElapsed (number) | runtime         |
| speed („slow“/“fast“)      | -                 | speed (string)                 | -                                           | -                        | -                    | -               |
| test status                | -                 | state (string)                 | -                                           | (event name)             | -                    | status          |
| Error object               | (QUnit.log())     | err (js error object)*         | (failedExpectations[0])                     | error (js error object)* | error (error object) | errors (array)º |
| total number of assertions | total (number)    | -                              | -                                           | assertions (number)      | -                    | -               |
| passed assertions          | passed (number))  | -                              | passedExpectations (array)                  | -                        | -                    | -               |
| failed assertions          | failed (number)   | -                              | failedExpectations (array)                  | -                        | -                    | -               |
| pending                    | skipped (boolean) | pending (boolean)              | pendingReason (string)                      | -                        | skipped (string)     | skipped         |
| parent suite               | -                 | parent (suite)                 | -                                           | -                        | -                    | -               |
| test timedOut              | -                 | timedOut (boolean)             | -                                           | -                        | -                    | -               |
| type                       | -                 | type (always „test“?) (string) | -                                           | -                        | -                    | -               |
| synchronous                | -                 | sync (boolean)                 | -                                           | -                        | isAsync              | -               |

*js error object has name (string), message (string) and stack (string)
º If this is provided as an array, it could be empty for passed tests, have one item for failed tests, and multiple items for frameworks like QUnit that don't use exceptions for regular failures.

### Error object
The attributes of the error object vary by framework and assertion library

| error object                                    | QUnit             | Mocha                        | Jasmine                    | Buster           | Intern             | JS Reporters |
|-------------------------------------------------|-------------------|------------------------------|----------------------------|------------------|--------------------|--------------|
| accessable by                                   | QUnit.log()       | test.err                     | test.failedExpectations[0] | test.error       | test.error         | test.errors  |
| errorName (AssertionError, ReferenceError etc.) | -                 | name (string)                | -                          | name (string)    | name (string)      | name         |
| errorMessage                                    | message (string)  | message (string)             | message (string)           | message (string) | message (string)   | message      |
| stacktrace                                      | source (string)   | stack (string)               | stack (string)             | stack (string)   | stack (string)     | stack        |
| expectedValue                                   | expected (object) | depends on assertion library | expected (object)          | -                | expected (object)  | expected     |
| actualValue                                     | actual (object)   | depends on assertion library | actual (object)            | -                | actual (object)    | actual       |
| matcherName                                     | -                 | -                            | matcherName (string)       | -                | -                  | -            |
| showDiff                                        | -                 | -                            | -                          | -                | showDiff (boolean) | -            |

Legend:
( - ) not available
( ? ) not defined, yet

I started working on adapters for QUnit and Jasmine over the last two weeks [fcarstens/js-test-examples](https://github.com/fcarstens/js-test-examples). The idea is that these represent the latest status of the proposal. Are we missing any attributes in the tables? Is there anything else we want to see included?

**Comment by jzaefferer** [comment]
Now that we have a mostly complete proposal for the js-reporters event data, I'm hoping we can get people from various projects involved again. I'm trying to notify those mentioned or involved before, and a few we hadn't notified before:

* QUnit: @JamesMGreene @Krinkle @leobalter 
* Mocha: @boneskull @travisjeffery @mantoni
* Jasmine: @slackersoft @ragaskar
* BusterJS: @cjohansen @dwittner
* Intern: @csnover @jason0x43
* vows: @davglass @indexzero @JerrySievert
* node-tap: @isaacs
* tape: @substack @domenic @raynos

The tables above outline our research into existing event data, along with a proposal for js-reporters event data, to go along with the [existing proposal for event names](https://github.com/js-reporters/js-reporters#event-names). 

Where it says `status (enum)`, it refers to the discussion in #4, which still needs a proposal.

While we're working out the remaining details on the proposal, we're also implementing adapters for multiple frameworks, to be able to test js-reporters integrations before frameworks support the new interface natively. The work in progress is in #13.

**Comment by jzaefferer** [comment]
@fcarstens can you create a PR that updates the tables above, adds the remaining ones for other events, adds all that to a separate file and adds suggested event data to the main README? Maybe that format will be easier to review.

**Comment by Raynos** [comment]
@jzaefferer 

Tape outputs TAP and only TAP.

You can use https://www.npmjs.com/package/tap-out to get JSON out.

You can write something similar to tap-out that outputs js-reporters JSON.
