### ISSUE TITLE
aws codebuild reports integration

### ISSUE THREAD

**Issue by Leooo** [js-reporters/js-reporters#122]
Hello, this issue is to ask for information / guidance on integrating qunit (used through ember-qunit) with AWS Codebuild, more specifically display test reports in AWS.

Going through the AWS docs, my starting point is that:

* The following test reports formats are [accepted by codebuild](https://docs.aws.amazon.com/codebuild/latest/userguide/test-reporting.html):

Cucumber JSON
JUnit XML
NUnit XML
NUnit3 XML
TestNG XML
Visual Studio TRX

* [Jasmine](https://docs.aws.amazon.com/codebuild/latest/userguide/test-report-jasmine.html) and [Jest](https://docs.aws.amazon.com/codebuild/latest/userguide/test-report-jest.html) test reports are also compatible by AWS Codebuild test reports.

Any idea what would be the way forward when using js-reporters, for non-specialists? Would that be compatible with [AWS Codebuild reports](https://docs.aws.amazon.com/codebuild/latest/userguide/test-reporting.html)? If not, what would be needed to let them be?

Many thanks

**Comment by Leooo** [comment]
@flore77 @Krinkle please any idea? Thanks

**Comment by Krinkle** [comment]
The js-reporters project is still very much in an early stage. But if using QUnit, then probably a [plugin](https://qunitjs.com/plugins/) for it will do the job. If you're running it through something like Karma, then that may also have plugins available that do it for you.

Are you running it on Node.js CLI, or in the browser? If in the browser, how are you currently running it in integration?

**Comment by Leooo** [comment]
@Krinkle thanks for the response, I'm using `ember test` command to run the tests in my CI using [ember-qunit](https://github.com/emberjs/ember-qunit) (and actually [ember-exam](https://github.com/ember-cli/ember-exam) but I think that is a detail).

**Comment by Leooo** [comment]
I will investigate using plugins yes - not sure how to do using ember-qunit but I'll explore thanks.

**Comment by Leooo** [comment]
@Krinkle any hint on how to add such plugins into ember-qunit please? Not finding any issues / precedents for that, and the setup instructions in the addon are not very explicit (["include after the Qunit core script"](https://github.com/JamesMGreene/qunit-reporter-junit#new-api))

**Comment by Leooo** [comment]
update: have been shown https://github.com/simplabs/testem-gitlab-reporter by @turbo87 that may help

**Comment by Leooo** [comment]
@turbo87 adding https://github.com/simplabs/testem-gitlab-reporter + https://github.com/xdumaine/testem-multi-reporter as per the docs works like charm for codebuild reports thanks!
