### ISSUE TITLE
Adapters: Better test infrastructure

### ISSUE THREAD

**Issue by jzaefferer** [js-reporters/js-reporters#17]
From #15:

> Maybe we can build some more infrastructure around this for testing purposes, where the output of both tap and console reporter are shown in an element on the page? That way we can just look at the rendered page, instead of having to check the console.

> Somewhat related, we should verify that both reporters work when running inside a node process, outputting to the terminal.

**Comment by jzaefferer** [comment]
@JamesMGreene can you make me an owner for this repo (or the entire org) or add @fcarstens as a committer to this repo, or both?

**Comment by fcarstens** [comment]
Closed by #23.
