### ISSUE TITLE
Add examples to README

### ISSUE THREAD

**Issue by fcarstens** [js-reporters/js-reporters#27]
Add examples to README as discussed in https://github.com/js-reporters/js-reporters/pull/25#issuecomment-130709569.

**Comment by flore77** [comment]
@jzaefferer can you please explain better what kind of example should be added to the README?

**Comment by jzaefferer** [comment]
So about a year ago I wrote:

> we should have at least two examples, one with a flat and one with a multiple levels deep nested structure. Could be addressed in a separate PR, please file an issue in that case.

I'm thinking something like this:
```
describe("bla", function() {
  it("foo", ...)
})
```
will produce, among others, a runEnd event like this:
```
{
  name: ?
  suites: [...],
  tests: [...],
  status: "passed",
  ...
```
Then have a variation of that with nested suites.

When we discussed this briefly at the meeting on Monday, I thought that including a kind reference implementation, based on the one we wrote for browserstack-runner, could also be a useful example, showing how to write a reporter using the adapters (and eventually native implementations).
