### ISSUE TITLE
Use js-reporters via adapters in browserstack-runner

### ISSUE THREAD

**Issue by jzaefferer** [js-reporters/js-reporters#33]
Create a pull request to replace existing adapters with the js-reporters interface (and our adapters) in https://github.com/browserstack/browserstack-runner/

**Comment by jzaefferer** [comment]
@flore77 now that all three adapters are working well, let's give this a try?

**Comment by flore77** [comment]
Sure, I was looking also to #34.

**Comment by jzaefferer** [comment]
That also works, should be fine to do in parallel. Up to you what you start with. Either way its time to get more people and projects involved.

**Comment by jzaefferer** [comment]
@flore77 let's focus on integrating our adapters into browserstack-runner. I'm optimistic that they'll accept a PR. It'll show that this project is going somewhere.

**Comment by flore77** [comment]
@jzaefferer sure, I opened an [issue](https://github.com/browserstack/browserstack-runner/issues/157) on their repo, but no one answered yet.

**Comment by jzaefferer** [comment]
That's okay, let's work on a PR and present that.

**Comment by flore77** [comment]
Closed via https://github.com/browserstack/browserstack-runner/pull/159.
