### ISSUE TITLE
Propose using js-reporters interface in Mocha or Jasmine

### ISSUE THREAD

**Issue by jzaefferer** [js-reporters/js-reporters#34]
Needs some research and communication to see if there's any interest (file an issue), if so, prototype the integration in a pull request.

**Comment by cynicaldevil** [comment]
@jzaefferer Hi, I had contacted you via e-mail about contributing to this repo. You had suggested me to finish up the remaining work on the mocha adapter, and I think I will look in to it now.

**Comment by jzaefferer** [comment]
Yeah, though the place to start is #28. This issue here could be a next step.

**Comment by cynicaldevil** [comment]
Ah sorry, I had originally meant to reply to you on this issue ( #35 ) here, but I had multiple issues open on different tabs and in my hurry I accidentally commented on this one.

**Comment by Krinkle** [comment]
Closing per https://github.com/js-reporters/js-reporters/issues/133 since Mocha and Jasmine already support TAP.
