### ISSUE TITLE
Welcome new contributors

### ISSUE THREAD

**Issue by jzaefferer** [js-reporters/js-reporters#35]
When James originally started this effort, he did a good job getting people interested (there's still a lot of people with write access to this repo), but almost no one stuck around. My efforts last year getting the same people interested again didn't go anywhere either.

Maybe we need to recruit some new people, like https://twitter.com/searls or use different communication channels.

**Comment by boneskull** [comment]
fwiw I'm still interested in getting this done, but it's just been slow.

**Comment by jzaefferer** [comment]
Good to know! We'll be making lots of progress here as part of the Google Summer of Code project this year. At some point we're going to propose the js-reporters adapter as a Mocha reporter (or something along that line). Your feedback and integration help will be very welcome there!

Also let us know if there's a better option.

**Comment by keithamus** [comment]
I'm going to ping my fellow team members on the chai team; @lucasfcosta, @vieiralucas, @meeber, @shvaikalesh.

It might be worth bringing in contributors from other popular testing frameworks. I won't @ them all now but maybe worth reaching out to these people?

```
node-tape: @substack, @ljharb, @Raynos
node-tap: @isaacs
mocha: @Bamieh @dasilvacontin @markowsiak @Munter @ScottFreeCode
avajs: @jamestalmage @jfmengels @kevva @novemberborn @sindresorhus @sotojuan @vadimdemedes
jasmine: @amavisca @jboyens @sgravrock  @slackersoft @vinsonchuong
```

**Comment by trentmwillis** [comment]
I'd be very happy to have some more involvement on this project! We've more-or-less adopted the standard in QUnit (will be the default in 3.0), but haven't focused on it too much due to lack of interest recently.

**Comment by Krinkle** [comment]
@jonathanKingston @isaacs I've invited you both as experts in this area based on your work on [TAP](https://github.com/TestAnything/Specification) and more generally in the wider JavaScript ecosystem.

No obligations. Any input as member or otherwise hugely appreciated.

I'm currently working on getting CRI Version 1 into shape at https://github.com/js-reporters/js-reporters/issues/117.

**Comment by isaacs** [comment]
I'm happy to provide feedback as time allows.  But the big challenge, I think, is that TAP is perfectly adequate for node-tap, and some of the specification is not exactly a 1:1 match to the semantics of the TAP v-pseudo-14 style that node-tap and various CPAN tap modules provide.
