### ISSUE TITLE
Use JavaScript Standard Style

### ISSUE THREAD

**Issue by flore77** [js-reporters/js-reporters#44]
## Need

We need a clean and organize code base.

## Deliverables

A clean code, which is easy to read.

## Solution

Use [standard](https://www.npmjs.com/package/standard), which does not need any configuration, except for ignores.

**Comment by flore77** [comment]
@jzaefferer what do you think ? If you agree I will update the list with all the rules, that I consider necessary, and then we can add or remove some.

**Comment by frantic1048** [comment]
I'd recommend a complete rule set, or extend based on a complete one. Something like [AirBnB Style](https://github.com/airbnb/javascript), [Standard Style](https://github.com/feross/eslint-config-standard) or [Canonical Style](https://github.com/gajus/eslint-config-canonical). They set most rules at error level which restricts code style tightly, and the overall style could be very determinate.

How do you think about it ? @jzaefferer

**Comment by jzaefferer** [comment]
Let's try https://www.npmjs.com/package/standard here, that removes the need for configuration (except for ignores) and there's other tools building on top (like standard-format and editor plugins).

**Comment by flore77** [comment]
I'm ok with most rules, but the `no-semicolons` I really do not like, also [google style guide](https://google.github.io/styleguide/javascriptguide.xml#Semicolons) strictly recommends to use semicolons, because they can cause problems.

**Comment by flore77** [comment]
Are you ok with that rule @jza

**Comment by jzaefferer** [comment]
Yes, I wouldn't have suggested it otherwise. I've been writing JS just fine without semicolons for almost a year now. The two cases where they cause problems are prevented by the same tool, so its fine.

**Comment by flore77** [comment]
Alright then, I didn't knew that is handling also the problem cases :+1: I have never written without semicolon and I was afraid I will get some bugs.

I have updated the details of the issue, as also renamed it.
