### ISSUE TITLE
Update QUnit version and adapter to make use of nested modules support

### ISSUE THREAD

**Issue by jzaefferer** [js-reporters/js-reporters#47]
Newer QUnit versions support nested modules. Maybe that works well enough that we can use the same `test/referenceData.js` for all 3 adapters.

Would also be good to test QUnit 2.0.0-rc1 (or newer), to make sure our adapter works with that.

**Comment by jzaefferer** [comment]
@flore77 I think this would be a good next step. Should help bring the tests in line.

**Comment by flore77** [comment]
Sure :+1:

**Comment by flore77** [comment]
Solved in #58 and #60.
