### ISSUE TITLE
Fix Jasmine Adapter

### ISSUE THREAD

**Issue by flore77** [js-reporters/js-reporters#63]
After the [new testing](https://github.com/js-reporters/js-reporters/tree/9aba15bc8a801b5a1b8f0829b7fb534cfa46317a/test/integration) we need to fix some issues in the adapter.

## Issues

[1] Objects are **emitted** are then **mutated**. [Emitted](https://github.com/js-reporters/js-reporters/blob/e5c9a836dfeaa9288843c277c4c32ca954d784b4/lib/adapters/JasmineAdapter.js#L80) and [mutated](https://github.com/js-reporters/js-reporters/blob/e5c9a836dfeaa9288843c277c4c32ca954d784b4/lib/adapters/JasmineAdapter.js#L84-L91).

[2] Global tests have as suite name `Jasmine__TopLevel__Suite`, they should have undefined.

[3] Skipped tests as a Number for their runtime, it must be undefined.

[4] Replace and test Jasmine specific errors.

[5] Nested suite execution order.

## Solutions

- [x] [1] We should convert the `suites` and `tests` every time we are emitting something.

- [x] [2] Add a name only for [non global tests](https://github.com/js-reporters/js-reporters/blob/f4e50a63717038900144cfea2ad71f79325d6716/lib/adapters/JasmineAdapter.js#L83-L92).
- [x] [3] Set the runtime only for [non skipped](https://github.com/js-reporters/js-reporters/blob/e5c9a836dfeaa9288843c277c4c32ca954d784b4/lib/adapters/JasmineAdapter.js#L89) tests.

- [x] [4] Add a test especially to test Jasmine errors, like for the [QUnit errors](https://github.com/js-reporters/js-reporters/blob/e5c9a836dfeaa9288843c277c4c32ca954d784b4/test/integration/adapters.js#L73-L95). Also [override](https://github.com/js-reporters/js-reporters/blob/e5c9a836dfeaa9288843c277c4c32ca954d784b4/test/integration/adapters.js#L121) Jasmine errors.

- [x] [5] Jasmine runs suites and tests in source order, our [reference-data](https://github.com/js-reporters/js-reporters/blob/e5c9a836dfeaa9288843c277c4c32ca954d784b4/test/integration/reference-data.js#L121-L124) is not respecting this order, but until #62 is fixed, we can change the order in the Jasmine fixture by moving this [test](https://github.com/js-reporters/js-reporters/blob/e5c9a836dfeaa9288843c277c4c32ca954d784b4/test/fixtures/jasmine.js#L46-L48) before the `inner suite`.

**Comment by jzaefferer** [comment]
On [2], removing the suite name where needed should be easy enough, right?

The rest looks good.

**Comment by flore77** [comment]
> On [2], removing the suite name where needed should be easy enough, right?

Yes, but I didn't know what to write :laughing: the solution will come out from the implementation, then I will fill in.
