### ISSUE TITLE
Nested suite name

### ISSUE THREAD

**Issue by flore77** [js-reporters/js-reporters#65]
Currently only tests have as `suiteName` a concatenated name of the nested suites.

Example:

```js
describe('outer suite', function() {
  describe('inner suite', function() {
    it('test', function() {});
  });
});
```

emitted outer suite object:
```js
{
  name: outer suite,
  ...
}
```

emitted inner suite object:
```js
{
  name: inner suite
  ...
}
```

emitted test object:
```js
{
  testName: test,
  suiteName: outer suite inner suite
  ...
}
```

**Comment by jzaefferer** [comment]
Its somewhat inconsistent, but not unreasonable. What do you suggest to do here?

**Comment by flore77** [comment]
Yeah, it is a bit inconsistent.

I'm not sure I think we can add another property to represent the concatenated name, like:

```js
// emitted outer suite object
{
name: outer suite,
fullName: outer suite,
...
}  

// emitted inner suite object
{
name: inner suite
fullName: outter suite > inner suite
...
}

// emitted test object
{
testName: test,
suiteName: inner suite
fullname: outer suite > inner suite > test
...
}
```

The `fullname` prop can be the concatenated name, and we should use a character to separate it, `>` or `#` or something. 

Or it can be an array of names, like: 
```js
{
...
fullName: [outer suite, inner suite, test]
...
}
```

**Comment by flore77** [comment]
I think it may be useful, because I have seen that also [Karma](https://github.com/karma-runner/karma-mocha/blob/6dcb82a44f0c5e98c4c7172d79739820b6058de8/src/adapter.js#L123-L127) is building a concatenated name. I don't now yet at what is using it, but if it creates its it must be used at something.

**Comment by flore77** [comment]
@jzaefferer we should also continue this one.

**Comment by jzaefferer** [comment]
Sure, but I'd like to finish the browserstack-runner PR, so that they can review it.

**Comment by flore77** [comment]
@jzaefferer can I go for this ? I think also [browserstack](https://github.com/browserstack/browserstack-runner/blob/d14d04801fabb34bbd6a518fb6638b73356cdac5/lib/_patch/qunit-plugin.js#L50) would benefit from this.

**Comment by jzaefferer** [comment]
Would you replace https://github.com/browserstack/browserstack-runner/pull/159/files#diff-885d5623bc9f0fada7aa1bcdcdde5574R30 with `testName: test.fullName.join(" ")`?

Alternative property name: `canonicalName`?

**Comment by flore77** [comment]
> Would you replace https://github.com/browserstack/browserstack-runner/pull/159/files#diff-885d5623bc9f0fada7aa1bcdcdde5574R30 with testName: test.fullName.join(" ")?

Yes! So do we make the `test.fullName` an array of names ?

> Alternative property name: canonicalName?

Sure. But why this name ?

**Comment by jzaefferer** [comment]
Let's go with `fullName` as array.
