### ISSUE TITLE
Test suite's status and runtime props

### ISSUE THREAD

**Issue by flore77** [js-reporters/js-reporters#68]
Currently the testing does not verify the `status` and `runtime` props of `suites`.

This props are implemented through ES6 getters, so they have dynamically computed values.

I see 2 ways to test the props:

1 - To make the properties constant

2 - To create 2 new tests for this props

```js
it('test the suites statuses', function() {
  suites.forEach(function(suite, index) {
    expect(suite.status).to.be.equal(expectedSuitesStatus[index]);
  });
});

it('test the suites runtime to be a Number', function() {
  ...
});
```

I am open to other suggestions.

**Comment by jzaefferer** [comment]
Does it matter that the props a getters? From the users/clients/tests perspective, they should look like normal properties and we should be able to test them as such, no?

**Comment by flore77** [comment]
Yes, from the users/clients/etc. perspective it is perfectly fine, they are seeing them as normal props.

My problem is with their testing, because currently we are doing a `deep equal` comparison, I am not sure how it is implemented in `Chai`, if it is testing also this dynamic props, but it does not matter. 

It does not matter, because if it **verifies also this props, they will be for sure the same**, for the collected data and reference data, because I cannot set it explicitly in the reference data.

Example:
```js
var suite1 = new Suite('1', [], []);
var suite1Ref = new Suite('1', [], []);

expect(suite1).to.be.deep.equal(suite1Ref); // passes

console.log(suite1.status) // outputs: 'abc'
console.log(suite1Ref.status) // outputs: 'abc'
```

They will be equal, but if I have a bug, or a bad implemented `status` prop that returns a random string, I will not know and I will assume everything is fine.

**Comment by jzaefferer** [comment]
Oh, because the reference data is using the same computed property as the actual data. Then your 2nd suggestion makes sense, using separate tests for those computed properties.

**Comment by jzaefferer** [comment]
Or replacing them with regular properties, which might serialize better...
