### ISSUE TITLE
Helpers

### ISSUE THREAD

**Issue by flore77** [js-reporters/js-reporters#91]
While working on the [qunit integration](https://github.com/jquery/qunit/pull/1026), I added js-reporters as a dependency. In my opinion js-reporters should come with some helpers so that it will be easy to adopt the standard.

The scenario that I came through is that when I want to [emit](https://github.com/jquery/qunit/pull/1026/files#diff-7eb52b366866677666470e019283c8eaR251) an object (suite or test) , I don't want to emit the internal object, I want to emit a copy of it and I would like to have a function that would do this for me. Something like:

```js
export function createSuiteStart(suite) {
  return new Suite(
    suite.name,
    suite.fullName.slice(),
    suite.childSuites.map((childSuite) => createSuiteStart(childSuite)),
    suite.tests
  );
}

export function createSuiteEnd(suite) {
  ...
}
```

Also I came into a sort of problem, I am firstly creating the [suites](https://github.com/jquery/qunit/pull/1026/files#diff-7eb52b366866677666470e019283c8eaR61) with an empty array for tests, and then I am adding the [tests](https://github.com/jquery/qunit/pull/1026/files#diff-f6c2ded91c9881cdc31b5bfcabb54c3bR56) to it.

Our Suite implementation sees that there is no test and thinks that the suite has no tests and computes already the `status`, `testCounts` and `runtime`, although I need a `suite start` for which this properties should be be undefined.

If we implement the above functions the emitted objects will be correct (the `createSuiteStart` function will return a Suite with `status` etc. `undefined`). But internally the status of the suite will always be wrong (it will be passed), which I don't find ok.

Now I don't know if I should try to create the suites after I create the tests, or to change something in js-reporters. 

Maybe something like:

```js
class Suite (name, fullName, childSuites, tests, status, testCounts, runtime) {
  ...
  this.status = (arguments.length === 5) ? status : getStatus(this);
  this.testCounts = (arguments.length === 6) ? testCounts : getTestCounts(this);
  ...
}
```

or

```js
class SuiteStart(...) {
  ...
}

class SuiteEnd(...) {
  ...
}
```

**Comment by jzaefferer** [comment]
Helpers for cloning objects don't really belong here, but since there's more to it, I'm okay with addressing the issue.

At a glance, adding extra types for start and end events makes sense. We should consider doing that in the spec as well - can still extend one with the other. Like "SuiteStart has these properties: [...] SuiteEnd has the same properties as SuiteStart, with the following additional properties: [...]".
